import turtle
import random
screen = turtle.Screen()
screen.bgcolor("black")
# screen.getshapes("triangle")
screen.title("Mahabharat")
t = turtle.Turtle()
t.color("Red")
t.home()
t.right(30)
t.forward(100)
t.backward(100)
t.color("Blue")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Orange")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Pink")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Yellow")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Green")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Sky Blue")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Brown")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Purple")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Lavender")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Plum")
t.right(30)
t.forward(100)
t.backward(100)
t.color("Magenta")
t.right(30)
t.forward(100)
t.backward(100)
# t.hideturtle()
# turtle.done()



t.home()
t.penup()
t.goto(-200,0)
t.pendown()
for i in range(12):
    # t.color("red","yellow","orange","pink","purple","green","blue","brown")
    # random = ["red","yellow","orange","pink","purple","green","blue","brown"]
    t.color("yellow")
    # t.color("random")
    t.right(30)
    t.forward(100)
    t.backward(100)

t.hideturtle()
turtle.done()